image: beevelop/nodejs-python:latest

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install -g elm create-elm-app
          - elm-app install
          - elm-app test
          - elm-app build
          - pip install boto3==1.3.0
          - python aws/cfn_stack_update.py RaffleElmStack aws/stack.yaml
          - python aws/s3-empty-bucket.py raffleelm.abbsnabb.com
          - python aws/s3-upload-dir.py raffleelm.abbsnabb.com build true irrelevant